### ISSUE TITLE
What does inference.py produce ?

### ISSUE THREAD

**Issue by nestarz** [thusiyuan/holistic_scene_parsing#1]
Hi,

First, thanks for sharing and congratulation for your paper. 
I'm trying to replicate your results using your code and after running for 1h the inference using:
`python inference.py -lo 11`

I'm only getting purple or black png images of depth, segmentation and normal. (Also, I'm wondering where in the code you used a Neural Network to produce the 2D layout proposal.)

Thanks,
Elias

**Comment by nestarz** [comment]
I'm trying to Hello World with osmesa and PyOpenGL to see if the problem is there. Keep you updated. (If you have any Hello World code to help me, I would be grateful !)

Update:
I'm getting weird results using osmesa and python bindings.
```
osmesa.init_ctx(w,h)
osmesa.render()
osmesa.free_ctx()
```
![a](https://user-images.githubusercontent.com/5360876/44629520-ea689380-a950-11e8-9022-a34858a87b12.png)

This result is expected, nothing wrong yet.

But when I use my own code between osmesa.ini_ctx and osmesa.free_ctx. Nothing happen, and it seems to be why I have black images when running inference.py.

```
osmesa.init_ctx(w,h)
glClearColor(255, 0, 0, 0)
glShadeModel(GL_FLAT)

glClear(GL_COLOR_BUFFER_BIT) # Clear all pixels.
# Draw white polygon (rectangle) with corners at (0.25, 0.25, 0) and (0.75, 0.75, 0)
glColor3f(1, 1, 1)
glBegin(GL_POLYGON)
glVertex3f(0.25, 0.25, 0)
glVertex3f(0.75, 0.25, 0)
glVertex3f(0.75, 0.75, 0)
glVertex3f(0.25, 0.75, 0)
glEnd()
# Don't wait! Start processing buffered OpenGL routines.
glFlush()
osmesa.free_ctx()
```
Results is a black image.

Related issue: https://github.com/certik/osmesa/issues/1

**Comment by thusiyuan** [comment]
Hi,
We will push 'osmesa.pyx' file to the repo, you can try it again with this file.
Usually inference.py could produce reasonable result if you can pass the test example of osmesa.
Can you try to add 'osmesa.render()' in your example?

**Comment by nestarz** [comment]
Hi ! Thanks for your reply,

In fact I managed today to make it work by deleting the osmesa content and replacing everything by this python file:

https://gist.github.com/NestarZ/9b358dfbe2a730bc6be2f0b3c0e929fa

It's almost the same content as osdemo.c but only with python.

It works after doing this:

`apt-get update && apt-get install -y libosmesa6-dev freeglut3-dev
`

**Comment by nestarz** [comment]
There is a last problem I need to solve to replicate your awesome paper results and with your code.

1. How can I input a single RGB image to this algorithm that isn't in the data folder ?

I figured that every image have multiple files associated (a pickle file for pg, a depth map, a normal mal and a semgentation map). But what if I don't have them ?

Thanks,
Elias

**Comment by thusiyuan** [comment]
Nice! You can now try our examples.

The generating of initial parse graph is composed by several different modules, those modules could be run in some certain environments. We are still merging those modules currently. Hopefully they could be released in the following month.

**Comment by ETHRuiGong** [comment]
I encounter the same problem with nestarz, and I use the same way which replace the osmesa content with osmesa.py. But I get the following fault:
infer 3D room layout and 3D object for sample 11
enter infer_pg
loading CAD model
66cdea8432907e9fb99d331574136d26
bed exists and align success
f1b1e6d1cb875b9f11c3739edd52fa3
dresser exists and align success
1316780d9b4a8ca71bb088904f7cb154
night_stand exists and align success
b3836ad467e9f3157199c3a1b4ff8300
lamp exists and align success
859e9c3a93ad1f03e1f4f9b641386c6a
picture exists and align success
3d6b55fe2deb2aa3a1c746794f191dc8
night_stand exists and align success
b3836ad467e9f3157199c3a1b4ff8300
lamp exists and align success
CAD model loaded successfully
Depth=16 Stencil=8 Accum=0
Width=730 Height=530
**Segmentation fault**

I have already correct the scikit-learn version with "pip install scikit-learn==0.19.0". So could you please give me some advice?

Thanks a lot!
----------------------------------------------------------------------------------------------------------------------------------
The problem has already been solved with the solution of the "netstarz" that uses the osmesa.py file to replace the original osmesa content. But besides that, in order to be incompatible with the osmesa python file, some modifications should be made to the render_scene.py file as following:
Line 787 osmesa.init_ctx(width, height) should be replaced with: ctx, buf = osmesa.init_ctx(width, height)
Line 804: GL.glFlush() should be commented.
Line 806 osmesa.free_ctx("end") should be replaced with: osmesa.free_ctx(ctx,buf)
